(function(){
  'use strict';
  const PF=window.PF=window.PF||{};
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const zooms=[25,50,100,200,400,800,1600];
  const defaultPalette=['#0F172A','#FFFFFF','#64748B','#2563EB','#3B82F6','#7C3AED','#EF4444','#F97316','#F59E0B','#EAB308','#22C55E','#14B8A6','#06B6D4','#EC4899','#A855F7','#94A3B8','#CBD5E1','#334155'];
  const state={view:'home',theme:localStorage.getItem('pf-theme')||'system',pixelZoom:400,palette:[...defaultPalette],skinPalette:[...defaultPalette],pixelSym:'none',skinSym:'none',pixelDirty:false,animDirty:false,skinDirty:false,animTimer:null,animPlaying:false,animActive:0,animFrames:[],animW:32,animH:32,dragFrame:null};
  let pixelEngine,animEngine,skinEngine,skin3d;

  function toast(msg,type='ok'){const el=document.createElement('div');el.className='toast '+(type==='error'?'error':'');el.textContent=msg;$('#toastStack').appendChild(el);setTimeout(()=>el.remove(),2800)}
  function setTheme(theme){state.theme=theme;localStorage.setItem('pf-theme',theme);let effective=theme;if(theme==='system')effective=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=effective;$$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));$('#themeIcon').textContent=effective==='dark'?'☀':'◐'}
  function navigate(view){if(state.animPlaying)stopAnimation();state.view=view;$$('.view').forEach(v=>v.classList.toggle('is-visible',v.id==='view-'+view));$$('.nav-btn').forEach(b=>b.classList.toggle('is-active',b.dataset.view===view));if(view==='home')renderRecent();setTimeout(scheduleEditorFit,20);if(view==='skin')setTimeout(()=>skin3d?.resize(),30)}
  function updateColorChip(inputId,chipId,largeId){const v=$(inputId).value;$(chipId).style.background=v;if(largeId)$(largeId).style.background=v;}
  function setActiveColor(hex,targetInput,chipId,largeId){$(targetInput).value=hex;updateColorChip(targetInput,chipId,largeId)}
  function openFileDialog(id){$(id).value='';$(id).click()}
  function downloadText(blob,name){PF.Exporter.downloadBlob(blob,name)}
  function validateProject(obj){if(!obj||obj.format!=='PixelForge'||obj.version!==1)throw new Error('Invalid PixelForge project.');if(!['pixel-art','animation','minecraft-skin'].includes(obj.type))throw new Error('Unsupported project type.');if(!Number.isInteger(obj.width)||!Number.isInteger(obj.height)||obj.width<1||obj.width>128||obj.height<1||obj.height>128)throw new Error('Invalid project dimensions.');if(!Array.isArray(obj.frames)||obj.frames.length<1||obj.frames.length>120)throw new Error('Invalid frame count.');for(const f of obj.frames){if(!Array.isArray(f.pixels)||f.pixels.length!==obj.width*obj.height)throw new Error('Malformed frame data.');for(let i=0;i<f.pixels.length;i++){const n=Number(f.pixels[i]);if(!Number.isFinite(n))throw new Error('Invalid pixel color.');f.pixels[i]=n>>>0}}return obj}
  function readFileAsText(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error||new Error('Read failed'));r.readAsText(file)})}
  function saveProjectFile(project){PF.Exporter.saveHTD(project);toast('Project file exported successfully.')}
  function frameObj(pixels){return {pixels:new Uint32Array(pixels)}}

  function buildPixelProject(){return {format:'PixelForge',version:1,type:'pixel-art',name:$('#pixelProjectName').value.trim()||'Untitled Pixel Art',width:pixelEngine.width,height:pixelEngine.height,fps:8,frames:[frameObj(pixelEngine.pixels)],thumbnail:PF.Exporter.makeThumb(pixelEngine.width,pixelEngine.height,pixelEngine.pixels)}}
  function buildAnimProject(){commitAnimFrame();return {format:'PixelForge',version:1,type:'animation',name:$('#animProjectName').value.trim()||'Walk Animation',width:state.animW,height:state.animH,fps:Number($('#animFps').value),frames:state.animFrames.map(frameObj),thumbnail:PF.Exporter.makeThumb(state.animW,state.animH,state.animFrames[0])}}
  function buildSkinProject(){return {format:'PixelForge',version:1,type:'minecraft-skin',name:$('#skinProjectName').value.trim()||'My Minecraft Skin',width:64,height:64,fps:8,frames:[frameObj(skinEngine.pixels)],thumbnail:PF.Exporter.makeThumb(64,64,skinEngine.pixels)}}
  async function saveToStore(project){const p=await PF.Store.putProject(project);return p}
  async function persistProject(project,msg='Project saved successfully.'){try{const p=await saveToStore(project);toast(msg);return p}catch(e){toast(e.message||'Save failed','error');return null}}
  async function savePixel(openDownload=true){const project=buildPixelProject();if(openDownload)saveProjectFile(project);const p=await persistProject(project);if(p)state.pixelDirty=false;return p}
  async function saveAnimation(openDownload=true){const project=buildAnimProject();if(openDownload)saveProjectFile(project);const p=await persistProject(project);if(p)state.animDirty=false;return p}
  async function saveSkin(openDownload=true){const project=buildSkinProject();if(openDownload)saveProjectFile(project);const p=await persistProject(project);if(p)state.skinDirty=false;return p}

  function initPixel(){
    pixelEngine=new PF.PixelEngine($('#pixelCanvas'),{width:32,height:32,scale:32,showGrid:true,outline:true,color:'#2563EB',onChange:()=>{state.pixelDirty=true;updatePixelStatus()},onPick:c=>{if(c){const h=PF.rgbaToHex(c);setActiveColor(h,'#pixelColor','#colorChip','#bigColorChip')}}});
    bindPixelUI();renderPalette();updatePixelStatus();
  }
  function updatePixelStatus(){if(!pixelEngine)return;$('#pixelStatus').textContent=`${pixelEngine.width} × ${pixelEngine.height}`;$('#toolStatus').textContent=toolLabel(pixelEngine.tool);$('#zoomLabel').textContent=state.pixelZoom+'%';updateColorChip('#pixelColor','#colorChip','#bigColorChip');}
  function toolLabel(t){return ({pencil:'Pencil',eraser:'Eraser',fill:'Fill',eyedropper:'Eyedropper',line:'Line',rect:'Rectangle',darken:'Darken',lighten:'Lighten',clear:'Clear'})[t]||t}
  function fitEngineToWrap(engine,wrap,label){if(!engine||!wrap)return;const styles=getComputedStyle(wrap);const padW=(parseFloat(styles.paddingLeft)||0)+(parseFloat(styles.paddingRight)||0);const padH=(parseFloat(styles.paddingTop)||0)+(parseFloat(styles.paddingBottom)||0);const availableW=Math.max(1,wrap.clientWidth-padW-8);const availableH=Math.max(1,wrap.clientHeight-padH-8);const maxScale=Math.floor(Math.min(availableW/engine.width,availableH/engine.height));const scale=Math.max(1,maxScale);engine.scale=scale;engine.resize();if(label)label.textContent='FIT';}
  function fitPixel(){fitEngineToWrap(pixelEngine,$('#pixelCanvasWrap'),$('#zoomLabel'))}
  function setPixelZoom(z){state.pixelZoom=z;pixelEngine?.setScale(Math.max(1,Math.round(z/50)));updatePixelStatus()}
  function scheduleEditorFit(){requestAnimationFrame(()=>requestAnimationFrame(()=>{fitPixel();fitEngineToWrap(animEngine,$('#animCanvasWrap'));fitEngineToWrap(skinEngine,$('#skinCanvasWrap'));skin3d?.resize()}))}
  function selectPixelTool(tool){pixelEngine.setTool(tool);$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));updatePixelStatus()}
  function renderPalette(){const grid=$('#paletteGrid');grid.innerHTML='';state.palette.forEach(hex=>{const b=document.createElement('button');b.className='palette-swatch';b.style.background=hex;b.title=hex;b.setAttribute('aria-label','Choose '+hex);b.addEventListener('click',()=>{setActiveColor(hex,'#pixelColor','#colorChip','#bigColorChip');pixelEngine.setColor(hex)});grid.appendChild(b)});updateColorChip('#pixelColor','#colorChip','#bigColorChip')}
  function changePixelSize(){const n=Number($('#pixelSize').value);pixelEngine.setDimensions(n,n);state.pixelDirty=true;updatePixelStatus();scheduleEditorFit();toast(`New ${n} × ${n} canvas created.`)}
  function importPNG(file,engine,onDone,expected){const img=new Image();img.onload=()=>{try{if(expected&& (img.naturalWidth!==expected||img.naturalHeight!==expected))throw new Error(`Image must be exactly ${expected} × ${expected}.`);const max=expected||128;const tw=expected||Math.min(img.naturalWidth,max),th=expected||Math.min(img.naturalHeight,max);const c=document.createElement('canvas');c.width=tw;c.height=th;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(img,0,0,tw,th);const d=ctx.getImageData(0,0,tw,th).data;const arr=new Uint32Array(tw*th);for(let i=0;i<arr.length;i++)arr[i]=PF.packRGBA(d[i*4],d[i*4+1],d[i*4+2],d[i*4+3]);engine.setDimensions(tw,th,arr);onDone?.();toast('PNG imported successfully.')}catch(e){toast(e.message||'Unable to import PNG.','error')}};img.onerror=()=>toast('Unsupported or invalid PNG.','error');img.src=URL.createObjectURL(file)}

  function bindPixelUI(){
    $$('[data-tool]').forEach(b=>b.addEventListener('click',()=>selectPixelTool(b.dataset.tool)));
    $('#pixelColor').addEventListener('input',()=>{pixelEngine.setColor($('#pixelColor').value);updateColorChip('#pixelColor','#colorChip','#bigColorChip')});
    $('#transparentBtn').addEventListener('click',()=>{pixelEngine.setColor(0);setActiveColor('#00000000','#pixelColor','#colorChip','#bigColorChip');toast('Transparent color selected.')});
    $('#pixelUndo').addEventListener('click',()=>pixelEngine.undo());$('#pixelRedo').addEventListener('click',()=>pixelEngine.redo());$('#pixelGrid').addEventListener('click',()=>{$('#showGrid').click()});
    $('#showGrid').addEventListener('change',()=>{pixelEngine.showGrid=$('#showGrid').checked;pixelEngine.render()});$('#checkerBg').addEventListener('change',()=>{pixelEngine.backgroundChecker=$('#checkerBg').checked;pixelEngine.render()});$('#outlinePixels').addEventListener('change',()=>{pixelEngine.outline=$('#outlinePixels').checked;pixelEngine.render()});
    $('#zoomOut').addEventListener('click',()=>{const i=Math.max(0,zooms.indexOf(state.pixelZoom)-1);setPixelZoom(zooms[i])});$('#zoomIn').addEventListener('click',()=>{const i=Math.min(zooms.length-1,zooms.indexOf(state.pixelZoom)+1);setPixelZoom(zooms[i])});$('#zoomFit').addEventListener('click',fitPixel);
    $$('.segmented [data-sym]').forEach(b=>b.addEventListener('click',()=>{$$('.segmented [data-sym]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.pixelSym=b.dataset.sym;pixelEngine.setSymmetry(state.pixelSym)}));
    $('#pixelSize').addEventListener('change',changePixelSize);$('#newPixelProject').addEventListener('click',()=>openNewModal());$('#modalCreate').addEventListener('click',createModalProject);
    $('#savePixel').addEventListener('click',()=>savePixel(true));$('#openPixel').addEventListener('click',()=>openFileDialog('#fileOpen'));$('#exportPixel').addEventListener('click',async()=>{try{await PF.Exporter.exportPNG(pixelEngine.width,pixelEngine.height,pixelEngine.pixels,$('#pixelProjectName').value||'pixel-art');toast('PNG exported successfully.')}catch(e){toast(e.message,'error')}});
    $('#addPaletteColor').addEventListener('click',()=>{const h=$('#pixelColor').value.toUpperCase();if(!state.palette.includes(h)){state.palette.push(h);renderPalette();savePreferences()}});
  }
  function openNewModal(){$('#modalProjectName').value=$('#pixelProjectName').value;$('#modalProjectSize').value=$('#pixelSize').value;$('#newProjectModal').classList.remove('hidden');setTimeout(()=>$('#modalProjectName').focus(),20)}
  function closeModal(id){$('#'+id).classList.add('hidden')}
  function createModalProject(){const name=$('#modalProjectName').value.trim()||'Untitled Pixel Art',n=Number($('#modalProjectSize').value);$('#pixelProjectName').value=name;$('#pixelSize').value=n;pixelEngine.setDimensions(n,n);state.pixelDirty=false;closeModal('newProjectModal');navigate('pixel');scheduleEditorFit();toast(`${n} × ${n} canvas created.`)}

  function initAnimation(){animEngine=new PF.PixelEngine($('#animCanvas'),{width:32,height:32,scale:32,showGrid:true,outline:true,color:'#2563EB',onChange:()=>{commitAnimFrame();state.animDirty=true;updateAnimStatus() },onPick:c=>{const h=PF.rgbaToHex(c);setActiveColor(h,'#animColor','#animColorChip');animEngine.setColor(c)}});state.animFrames=[new Uint32Array(animEngine.pixels)];updateAnimStatus();bindAnimationUI();renderTimeline();updateColorChip('#animColor','#animColorChip');scheduleEditorFit()}
  function commitAnimFrame(){if(!animEngine||!state.animFrames.length)return;state.animFrames[state.animActive]=new Uint32Array(animEngine.pixels)}
  function loadAnimFrame(i){commitAnimFrame();state.animActive=clampFrame(i);animEngine.setDimensions(state.animW,state.animH,state.animFrames[state.animActive]);updateAnimStatus();renderTimeline()}
  function clampFrame(i){return Math.max(0,Math.min(state.animFrames.length-1,i))}
  function updateAnimStatus(){if(!animEngine)return;$('#animStatus').textContent=`Frame ${state.animActive+1} / ${state.animFrames.length} · ${state.animW} × ${state.animH}`;$('#frameNumber').textContent=String(state.animActive+1).padStart(2,'0');$('#animToolStatus').textContent=toolLabel(animEngine.tool);$('#fpsOut').textContent=$('#animFps').value+' FPS'}
  function selectAnimTool(t){animEngine.setTool(t);$$('[data-anim-tool]').forEach(b=>b.classList.toggle('active',b.dataset.animTool===t));updateAnimStatus()}
  function renderTimeline(){const wrap=$('#timelineFrames');wrap.innerHTML='';state.animFrames.forEach((p,i)=>{const item=document.createElement('div');item.className='timeline-item'+(i===state.animActive?' active':'');item.draggable=true;const c=document.createElement('canvas');c.width=74;c.height=74;c.getContext('2d').imageSmoothingEnabled=false;const thumb=PF.Exporter.canvasFromPixels(state.animW,state.animH,p,74/state.animW);c.getContext('2d').drawImage(thumb,0,0,74,74);item.appendChild(c);const s=document.createElement('small');s.textContent=String(i+1).padStart(2,'0');item.appendChild(s);item.addEventListener('click',()=>loadAnimFrame(i));item.addEventListener('dragstart',()=>{state.dragFrame=i});item.addEventListener('dragover',e=>e.preventDefault());item.addEventListener('drop',e=>{e.preventDefault();if(state.dragFrame===null||state.dragFrame===i)return;commitAnimFrame();const [f]=state.animFrames.splice(state.dragFrame,1);state.animFrames.splice(i,0,f);state.animActive=i;state.dragFrame=null;loadAnimFrame(i)});wrap.appendChild(item)});const mini=$('#timelineMini');mini.innerHTML='';const c=document.createElement('canvas');c.width=140;c.height=140;c.getContext('2d').drawImage(PF.Exporter.canvasFromPixels(state.animW,state.animH,state.animFrames[state.animActive],140/state.animW),0,0,140,140);mini.appendChild(c)}
  function addFrame(){commitAnimFrame();state.animFrames.splice(state.animActive+1,0,new Uint32Array(state.animW*state.animH));state.animActive++;animEngine.setDimensions(state.animW,state.animH,state.animFrames[state.animActive]);state.animDirty=true;renderTimeline();updateAnimStatus();toast('Frame added.')}
  function duplicateFrame(){commitAnimFrame();state.animFrames.splice(state.animActive+1,0,new Uint32Array(state.animFrames[state.animActive]));state.animActive++;animEngine.setDimensions(state.animW,state.animH,state.animFrames[state.animActive]);state.animDirty=true;renderTimeline();updateAnimStatus();toast('Frame duplicated.')}
  function deleteFrame(){if(state.animFrames.length<=1){toast('Animation must contain at least one frame.','error');return}commitAnimFrame();state.animFrames.splice(state.animActive,1);state.animActive=clampFrame(state.animActive);animEngine.setDimensions(state.animW,state.animH,state.animFrames[state.animActive]);state.animDirty=true;renderTimeline();updateAnimStatus();toast('Frame deleted.')}
  function bindAnimationUI(){
    $$('[data-anim-tool]').forEach(b=>b.addEventListener('click',()=>selectAnimTool(b.dataset.animTool)));$('#animColor').addEventListener('input',()=>{animEngine.setColor($('#animColor').value);updateColorChip('#animColor','#animColorChip')});
    $('#animUndo').addEventListener('click',()=>animEngine.undo());$('#animRedo').addEventListener('click',()=>animEngine.redo());$('#addFrame').addEventListener('click',addFrame);$('#dupFrame').addEventListener('click',duplicateFrame);$('#deleteFrame').addEventListener('click',deleteFrame);$('#clearFrame').addEventListener('click',()=>{animEngine.pushHistory();animEngine.pixels.fill(0);animEngine.render();commitAnimFrame();renderTimeline();state.animDirty=true});$('#animFps').addEventListener('input',updateAnimStatus);
    $('#newAnimation').addEventListener('click',()=>{if(!confirmIfDirty('animation'))return;state.animW=Number($('#animSize').value);state.animH=state.animW;state.animFrames=[new Uint32Array(state.animW*state.animH)];state.animActive=0;animEngine.setDimensions(state.animW,state.animH,state.animFrames[0]);renderTimeline();updateAnimStatus();state.animDirty=false});$('#animSize').addEventListener('change',()=>$('#newAnimation').click());
    $('#playAnim').addEventListener('click',playAnimation);$('#pauseAnim').addEventListener('click',pauseAnimation);$('#stopAnim').addEventListener('click',stopAnimation);$('#loopAnim').addEventListener('change',()=>{});$('#onionAnim').addEventListener('change',()=>{animEngine.render($('#onionAnim').checked&&state.animActive>0?state.animFrames[state.animActive-1]:null)});
    $('#saveAnimation').addEventListener('click',()=>saveAnimation(true));$('#openAnimation').addEventListener('click',()=>openFileDialog('#fileOpen'));$('#exportSprite').addEventListener('click',async()=>{try{commitAnimFrame();await PF.Exporter.exportSpriteSheet(state.animFrames,state.animW,state.animH,$('#animProjectName').value,'grid');toast('Sprite sheet exported successfully.')}catch(e){toast(e.message||'Export failed.','error')}});$('#exportGif').addEventListener('click',async()=>{try{commitAnimFrame();await PF.Exporter.exportGIF(state.animFrames,state.animW,state.animH,Number($('#animFps').value),$('#animProjectName').value);toast('GIF exported successfully.')}catch(e){toast(e.message||'GIF export failed.','error')}})
  }
  function playAnimation(){if(state.animPlaying)return;state.animPlaying=true;const tick=()=>{if(!state.animPlaying)return;const next=state.animActive+1;if(next>=state.animFrames.length){if($('#loopAnim').checked)state.animActive=0;else{state.animActive=state.animFrames.length-1;stopAnimation();return}}else state.animActive=next;animEngine.setDimensions(state.animW,state.animH,state.animFrames[state.animActive]);updateAnimStatus();renderTimeline();if($('#onionAnim').checked&&state.animActive>0)animEngine.render(state.animFrames[state.animActive-1]);state.animTimer=setTimeout(tick,1000/Number($('#animFps').value))};state.animTimer=setTimeout(tick,1000/Number($('#animFps').value));toast('Animation playing.')}
  function pauseAnimation(){if(!state.animPlaying)return;state.animPlaying=false;clearTimeout(state.animTimer);toast('Animation paused.')}
  function stopAnimation(){state.animPlaying=false;clearTimeout(state.animTimer);state.animTimer=null;if(!animEngine)return;state.animActive=0;animEngine.setDimensions(state.animW,state.animH,state.animFrames[0]);updateAnimStatus();renderTimeline()}

  function initSkin(){skinEngine=new PF.PixelEngine($('#skinCanvas'),{width:64,height:64,scale:16,showGrid:true,outline:true,color:'#E1A46F',onChange:()=>{state.skinDirty=true;skin3d?.setPixels(skinEngine.pixels);drawSkinGuides()},onPick:c=>{setActiveColor(PF.rgbaToHex(c),'#skinColor','#skinColorChip');skinEngine.setColor(c)}});skin3d=new PF.Skin3D($('#skin3d'));skin3d.setPixels(skinEngine.pixels);bindSkinUI();renderSkinPalette();updateColorChip('#skinColor','#skinColorChip');wrapSkinRender();scheduleEditorFit();}
  function wrapSkinRender(){const original=skinEngine.render.bind(skinEngine);skinEngine._baseRender=original;skinEngine.render=function(overlay){original(overlay);drawSkinGuides()};skinEngine.render()}
  function drawSkinGuides(){if(!skinEngine||!$('#skinGridToggle').checked)return;const ctx=skinEngine.ctx,s=skinEngine.renderScale,rects=[
    {x:8,y:8,w:8,h:8,c:'rgba(96,165,250,.65)'},{x:20,y:20,w:8,h:12,c:'rgba(167,139,250,.65)'},{x:4,y:20,w:4,h:12,c:'rgba(52,211,153,.65)'},{x:36,y:52,w:4,h:12,c:'rgba(52,211,153,.65)'},{x:40,y:8,w:8,h:8,c:'rgba(251,191,36,.65)'},{x:44,y:36,w:4,h:12,c:'rgba(251,191,36,.65)'}];ctx.save();ctx.lineWidth=Math.max(1,s>8?1.5:1);for(const r of rects){ctx.strokeStyle=r.c;ctx.strokeRect(r.x*s+.5,r.y*s+.5,r.w*s,r.h*s)}ctx.restore()}
  function selectSkinTool(t){skinEngine.setTool(t);$$('[data-skin-tool]').forEach(b=>b.classList.toggle('active',b.dataset.skinTool===t));$('#skinToolStatus').textContent=toolLabel(t)}
  function renderSkinPalette(){const grid=$('#skinPalette');grid.innerHTML='';state.skinPalette.forEach(hex=>{const b=document.createElement('button');b.className='palette-swatch';b.style.background=hex;b.title=hex;b.addEventListener('click',()=>{setActiveColor(hex,'#skinColor','#skinColorChip');skinEngine.setColor(hex)});grid.appendChild(b)});updateColorChip('#skinColor','#skinColorChip')}
  function bindSkinUI(){
    $$('[data-skin-tool]').forEach(b=>b.addEventListener('click',()=>selectSkinTool(b.dataset.skinTool)));$('#skinColor').addEventListener('input',()=>{skinEngine.setColor($('#skinColor').value);updateColorChip('#skinColor','#skinColorChip')});$('#skinUndo').addEventListener('click',()=>skinEngine.undo());$('#skinRedo').addEventListener('click',()=>skinEngine.redo());$('#skinGrid').addEventListener('click',()=>$('#skinGridToggle').click());$('#skinGridToggle').addEventListener('change',()=>{skinEngine.showGrid=$('#skinGridToggle').checked;skinEngine.render()});
    $$('.skin-sym [data-skin-sym]').forEach(b=>b.addEventListener('click',()=>{$$('.skin-sym [data-skin-sym]').forEach(x=>x.classList.remove('active'));b.classList.add('active');skinEngine.setSymmetry(b.dataset.skinSym)}));
    $('#importSkin').addEventListener('click',()=>openFileDialog('#skinOpen'));$('#exportSkin').addEventListener('click',async()=>{try{await PF.Exporter.exportPNG(64,64,skinEngine.pixels,$('#skinProjectName').value||'minecraft-skin');toast('Skin PNG exported successfully.')}catch(e){toast(e.message,'error')}});$('#saveSkin').addEventListener('click',()=>saveSkin(true));$('#openSkin').addEventListener('click',()=>openFileDialog('#fileOpen'));$('#addSkinPalette').addEventListener('click',()=>{const h=$('#skinColor').value.toUpperCase();if(!state.skinPalette.includes(h)){state.skinPalette.push(h);renderSkinPalette();savePreferences()}});
    $('#frontSkin').addEventListener('click',()=>skin3d.setView('front'));$('#backSkin').addEventListener('click',()=>skin3d.setView('back'));$('#resetSkin').addEventListener('click',()=>skin3d.reset())
  }

  async function handleHTDFile(file){try{const obj=validateProject(JSON.parse(await readFileAsText(file)));if(obj.type==='pixel-art'){navigate('pixel');$('#pixelProjectName').value=obj.name;$('#pixelSize').value=obj.width;pixelEngine.setDimensions(obj.width,obj.height,obj.frames[0].pixels);state.pixelDirty=false;scheduleEditorFit();toast('Pixel project opened successfully.')}else if(obj.type==='animation'){navigate('animation');state.animW=obj.width;state.animH=obj.height;state.animFrames=obj.frames.map(f=>new Uint32Array(f.pixels));state.animActive=0;$('#animProjectName').value=obj.name;$('#animFps').value=obj.fps||8;animEngine.setDimensions(obj.width,obj.height,state.animFrames[0]);updateAnimStatus();renderTimeline();state.animDirty=false;scheduleEditorFit();toast('Animation project opened successfully.')}else{navigate('skin');$('#skinProjectName').value=obj.name;skinEngine.setDimensions(64,64,obj.frames[0].pixels);state.skinDirty=false;skin3d.setPixels(skinEngine.pixels);scheduleEditorFit();toast('Skin project opened successfully.')}}catch(e){toast(e.message||'Unable to open this project.','error')}}

  function renderRecent(){PF.Store.loadRecent().then(list=>{const wrap=$('#recentProjects');wrap.innerHTML='';if(!list.length){wrap.innerHTML='<div class="empty-state"><div class="empty-icon">□</div><strong>No projects yet</strong><span>Start creating your first project.</span></div>';return}list.slice(0,6).forEach(p=>{const card=document.createElement('div');card.className='recent-card';const img=document.createElement('img');img.className='recent-thumb';if(p.thumb)img.src=p.thumb;const info=document.createElement('div');info.className='recent-info';const title=document.createElement('strong');title.textContent=p.name;const meta=document.createElement('span');meta.textContent=`${p.width}×${p.height} · ${p.type==='animation'?(p.frames||1)+' Frames':p.type==='minecraft-skin'?'Minecraft Skin':'Pixel Art'}`;info.append(title,meta);card.append(img,info);card.addEventListener('click',async()=>{const full=await PF.Store.getProject(p.id);if(full)loadProjectObject(full)});wrap.appendChild(card)})})}
  function loadProjectObject(p){if(p.type==='pixel-art'){navigate('pixel');$('#pixelProjectName').value=p.name;pixelEngine.setDimensions(p.width,p.height,p.frames[0].pixels);state.pixelDirty=false;scheduleEditorFit()}else if(p.type==='animation'){navigate('animation');state.animW=p.width;state.animH=p.height;state.animFrames=p.frames.map(f=>new Uint32Array(f.pixels));state.animActive=0;$('#animProjectName').value=p.name;$('#animFps').value=p.fps||8;animEngine.setDimensions(p.width,p.height,state.animFrames[0]);renderTimeline();updateAnimStatus();state.animDirty=false;scheduleEditorFit()}else{navigate('skin');$('#skinProjectName').value=p.name;skinEngine.setDimensions(64,64,p.frames[0].pixels);state.skinDirty=false;skin3d.setPixels(skinEngine.pixels);scheduleEditorFit()}}
  function confirmIfDirty(type){const dirty=type==='pixel'?state.pixelDirty:type==='animation'?state.animDirty:state.skinDirty;if(dirty)return confirm('You have unsaved changes. Continue without saving?');return true}
  function savePreferences(){localStorage.setItem('pf-palette',JSON.stringify(state.palette));localStorage.setItem('pf-skin-palette',JSON.stringify(state.skinPalette));localStorage.setItem('pf-grid-default',$('#showGrid')?.checked?'1':'0');localStorage.setItem('pf-outline-default',$('#outlinePixels')?.checked?'1':'0')}
  function loadPreferences(){try{state.palette=JSON.parse(localStorage.getItem('pf-palette')||JSON.stringify(defaultPalette));state.skinPalette=JSON.parse(localStorage.getItem('pf-skin-palette')||JSON.stringify(defaultPalette))}catch{}if($('#showGrid'))$('#showGrid').checked=localStorage.getItem('pf-grid-default')!=='0';if($('#outlinePixels'))$('#outlinePixels').checked=localStorage.getItem('pf-outline-default')!=='0'}
  function setupCanvasAutoFit(){
    const targets=[[pixelEngine,'#pixelCanvasWrap','#zoomLabel'],[animEngine,'#animCanvasWrap',null],[skinEngine,'#skinCanvasWrap',null]];
    if('ResizeObserver' in window){
      const ro=new ResizeObserver(entries=>{
        for(const entry of entries){
          const match=targets.find(([,selector])=>$(selector)===entry.target);
          if(match)fitEngineToWrap(match[0],entry.target,match[2]?$(match[2]):null);
        }
      });
      targets.forEach(([,selector])=>{const el=$(selector);if(el)ro.observe(el)});
    } else window.addEventListener('resize',scheduleEditorFit);
    window.addEventListener('resize',scheduleEditorFit);
  }

  function setupGlobal(){
    setTheme(state.theme);loadPreferences();setTimeout(()=>{if(pixelEngine){pixelEngine.showGrid=$('#showGrid').checked;pixelEngine.outline=$('#outlinePixels').checked;pixelEngine.render()}},0);
    $$('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));$('#settingsBtn').addEventListener('click',()=>navigate('settings'));$('#themeBtn').addEventListener('click',()=>setTheme(state.theme==='dark'?'light':state.theme==='light'?'system':'dark'));
    $('#startCreating').addEventListener('click',()=>navigate('pixel'));$('#openProjectHome').addEventListener('click',()=>openFileDialog('#fileOpen'));$('#clearRecent').addEventListener('click',async()=>{if(confirm('Clear recent projects and local project data?')){await PF.Store.clearAll();renderRecent();toast('Local project data cleared.')}});
    $('#fileOpen').addEventListener('change',e=>{const f=e.target.files[0];if(f)handleHTDFile(f)});$('#pngOpen').addEventListener('change',e=>{const f=e.target.files[0];if(f)importPNG(f,pixelEngine,()=>{state.pixelDirty=true})});$('#skinOpen').addEventListener('change',e=>{const f=e.target.files[0];if(f)importPNG(f,skinEngine,()=>{state.skinDirty=true;skin3d.setPixels(skinEngine.pixels)},64)});
    $$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.closeModal)));$('#newProjectModal').addEventListener('click',e=>{if(e.target.id==='newProjectModal')closeModal('newProjectModal')});
    $$('[data-theme]').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.theme)));$('#clearLocalData').addEventListener('click',async()=>{if(confirm('Clear all PixelForge local project data and preferences?')){await PF.Store.clearAll();localStorage.removeItem('pf-theme');localStorage.removeItem('pf-palette');localStorage.removeItem('pf-skin-palette');toast('Local data cleared.');location.reload()}});
    document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(tag==='INPUT'||tag==='SELECT'||tag==='TEXTAREA')return;if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();state.view==='pixel'?pixelEngine.undo():state.view==='animation'?animEngine.undo():state.view==='skin'&&skinEngine.undo()}else if(e.ctrlKey&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))){e.preventDefault();state.view==='pixel'?pixelEngine.redo():state.view==='animation'?animEngine.redo():state.view==='skin'&&skinEngine.redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();state.view==='pixel'?savePixel(true):state.view==='animation'?saveAnimation(true):state.view==='skin'&&saveSkin(true)}else if(e.ctrlKey&&e.key.toLowerCase()==='o'){e.preventDefault();openFileDialog('#fileOpen')}else if(e.key.toLowerCase()==='b')state.view==='pixel'?selectPixelTool('pencil'):state.view==='animation'?selectAnimTool('pencil'):state.view==='skin'&&selectSkinTool('pencil');else if(e.key.toLowerCase()==='e')state.view==='pixel'?selectPixelTool('eraser'):state.view==='animation'?selectAnimTool('eraser'):state.view==='skin'&&selectSkinTool('eraser');else if(e.key.toLowerCase()==='g')state.view==='pixel'?selectPixelTool('fill'):state.view==='animation'?selectAnimTool('fill'):state.view==='skin'&&selectSkinTool('fill');else if(e.key.toLowerCase()==='i')state.view==='pixel'?selectPixelTool('eyedropper'):state.view==='animation'?selectAnimTool('eyedropper'):state.view==='skin'&&selectSkinTool('eyedropper')});
    window.addEventListener('beforeunload',e=>{if(state.pixelDirty||state.animDirty||state.skinDirty){e.preventDefault();e.returnValue=''}});
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')setTheme('system')});
  }
  function boot(){initPixel();initAnimation();initSkin();setupGlobal();renderRecent();navigate('home');updateColorChip('#pixelColor','#colorChip','#bigColorChip');updateColorChip('#animColor','#animColorChip');updateColorChip('#skinColor','#skinColorChip');}
  boot();
})();
