(function(){
  'use strict';
  const PF=window.PF=window.PF||{}; const DB_NAME='PixelForgeDB',DB_VER=1,STORE='projects';
  const RecentKey='pixelforge-recent-v1';
  let dbPromise=null;
  function openDB(){if(!('indexedDB' in window))return Promise.reject(new Error('IndexedDB unavailable'));if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VER);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('updatedAt','updatedAt')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB error'))});return dbPromise}
  function id(){return 'p_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
  function putProject(p){p={...p,id:p.id||id(),updatedAt:Date.now()};return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(p);tx.oncomplete=()=>{updateRecent(p);resolve(p)};tx.onerror=()=>reject(tx.error||new Error('Save failed'))})).catch(()=>{try{localStorage.setItem('pixelforge-fallback-'+p.id,JSON.stringify(p));updateRecent(p);return p}catch(e){throw new Error('Local storage unavailable')}})}
  function allProjects(){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result.sort((a,b)=>b.updatedAt-a.updatedAt));req.onerror=()=>reject(req.error)})).catch(()=>{const arr=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('pixelforge-fallback-')){try{arr.push(JSON.parse(localStorage.getItem(k)))}catch{}}}return arr.sort((a,b)=>b.updatedAt-a.updatedAt)})}
  function getProject(pid){return openDB().then(db=>new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(pid);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})).catch(()=>{try{const x=localStorage.getItem('pixelforge-fallback-'+pid);return x?JSON.parse(x):null}catch{return null}})}
  function deleteProject(pid){return openDB().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(pid);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})).catch(()=>{localStorage.removeItem('pixelforge-fallback-'+pid)}).then(()=>loadRecent().then(r=>{const n=r.filter(x=>x.id!==pid);localStorage.setItem(RecentKey,JSON.stringify(n.slice(0,10)));return n}))}
  function updateRecent(p){const entry={id:p.id,name:p.name,type:p.type,width:p.width,height:p.height,frames:p.frames?.length||1,updatedAt:p.updatedAt,thumb:p.thumbnail||null};loadRecent().then(list=>{const next=[entry,...list.filter(x=>x.id!==p.id)].slice(0,12);localStorage.setItem(RecentKey,JSON.stringify(next))})}
  function loadRecent(){try{return Promise.resolve(JSON.parse(localStorage.getItem(RecentKey)||'[]'))}catch{return Promise.resolve([])}}
  async function clearAll(){try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch{}for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&k.startsWith('pixelforge-fallback-'))localStorage.removeItem(k)}localStorage.removeItem(RecentKey)}
  PF.Store={putProject,allProjects,getProject,deleteProject,loadRecent,clearAll};
})();
